---
#- name: install npm and nodejs
#  become: yes
#  apt:
#    name: ["nodejs", "npm"]
#    state: latest
#    update_cache: yes

#- name: "install pm2"
#  become: yes
#  npm:
#    name: pm2
#    global: yes
#    production: yes
#    state: present

- name: kill  pm2
  become: yes
  command: pm2 kill 

- name: "Where am I?"
  shell: pwd
  register: pwd_info
  debug:
    msg: "{{pwd_info.stdout_lines}}"

- name: "List current folder"
  shell: ls -al
  register: ls_info

- debug:
    msg: "{{ls_info.stdout_lines}}"

- name: Create project folders
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  with_items:
  - .circleci
  - .circleci/ansible

- name: Extract the archive file 
  become: yes
  ansible.builtin.unarchive:
    src: /root/project/artifact.tar.gz 
    dest: /root//project
    keep_newer: no
    mode: 0644
#    remote_src: yes

- name: printenv
  become: yes
  shell: printenv
  register: env_info
    
- debug:
    msg: "{{env_info.stdout_lines}}"


