---
#- name: install npm and nodejs
#  become: yes
#  apt:
#    name: ["nodejs", "npm"]
#    state: latest
#    update_cache: yes

#- name: "install pm2"
#  become: yes
#  npm:
#    name: pm2
#    global: yes
#    production: yes
#    state: present

- name: kill  pm2
  become: yes
  command: pm2 kill 


- name: Create a text file in opt directory using /bin/sh shell
  ansible.builtin.shell: echo "I am creating a new file" > /opt/new_file.txt
  become: true   # Ensure that the highest permissions are used on the remote host

- name: "Where am I?"
  ansible.builtin.shell: pwd
  register: pwd_info
  debug:
    msg: "{{pwd_info.stdout_lines}}"

- name: "List current folder"
  ansible.builtin.shell: ls -al
  register: ls_info

- debug:
    msg: "{{ls_info.stdout_lines}}"

- name: "sudo su -"
  become: true
  ansible.builtin.shell: sudo su -

- name: Create project folders
  ansible.builtin.file:
    state: directory
    dest: ~/project/
#  with_items:
#  - ~/project/
#  - ~/project/backend
#  - ~/project/.circleci
#  - ~/project/.circleci/ansible

- name: Extract the archive file 
  ansible.builtin.unarchive:
    src: /root/project/artifact.tar.gz 
    dest: ~/project/backend
    keep_newer: no
    mode: 0644
#    remote_src: yes

- name: printenv
  become: yes
  shell: printenv
  register: env_info
    
- debug:
    msg: "{{env_info.stdout_lines}}"


