---
- name: "install dependencies"
  become: yes
  apt:
    name: "npm"
    state: latest
    update_cache: yes

- name: Stop pm2
  become: yes
  command: pm2 stop all

- name: Start pm2
  become: yes
  command: pm2 start npm

- name: Extract the archive file 
  ansible.builtin.unarchive:
    src: ~/project/backend/artifact.tar.gz 
    dest: . 
    keep_newer: no
    mode: 0644
    remote_src: yes

